/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package brain;

import io.vertx.core.Vertx;
import io.vertx.core.eventbus.EventBus;

public class App {

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        EventBus eventBus = vertx.eventBus();
    }
}
