/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package brain;

import java.util.HashSet;
import java.util.Set;

import io.vertx.core.Vertx;
import io.vertx.core.eventbus.EventBus;

public class App {

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        EventBus eventBus = vertx.eventBus();
        Set<Node> nodes = new HashSet<>();
    }
}
